# Generated by Django 3.1.7 on 2024-03-09 09:08

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=Api.models.generate_random_room_code, max_length=8, unique=True),
        ),
    ]
